/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN_COMMENT = 6;
  /** RegularExpression Id. */
  int END_COMMENT = 7;
  /** RegularExpression Id. */
  int COMMENT = 8;
  /** RegularExpression Id. */
  int ABSTRACT = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int CASE = 12;
  /** RegularExpression Id. */
  int CATCH = 13;
  /** RegularExpression Id. */
  int CONTINUE = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int DEFLT = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int DOUBLE = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int EXTENDS = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int FINALLY = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int IMPORT = 26;
  /** RegularExpression Id. */
  int IMPLEMENTS = 27;
  /** RegularExpression Id. */
  int INTERFACE = 28;
  /** RegularExpression Id. */
  int INSTANCEOF = 29;
  /** RegularExpression Id. */
  int INT = 30;
  /** RegularExpression Id. */
  int LONG = 31;
  /** RegularExpression Id. */
  int NEW = 32;
  /** RegularExpression Id. */
  int NULL = 33;
  /** RegularExpression Id. */
  int PACKAGE = 34;
  /** RegularExpression Id. */
  int PRIVATE = 35;
  /** RegularExpression Id. */
  int PROTECTED = 36;
  /** RegularExpression Id. */
  int PUBLIC = 37;
  /** RegularExpression Id. */
  int RETURN = 38;
  /** RegularExpression Id. */
  int STATIC = 39;
  /** RegularExpression Id. */
  int SUPER = 40;
  /** RegularExpression Id. */
  int SWITCH = 41;
  /** RegularExpression Id. */
  int THIS = 42;
  /** RegularExpression Id. */
  int THROW = 43;
  /** RegularExpression Id. */
  int THROWS = 44;
  /** RegularExpression Id. */
  int TRUE = 45;
  /** RegularExpression Id. */
  int TRY = 46;
  /** RegularExpression Id. */
  int VOID = 47;
  /** RegularExpression Id. */
  int WHILE = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int DOT = 50;
  /** RegularExpression Id. */
  int LBRACK = 51;
  /** RegularExpression Id. */
  int LCURLY = 52;
  /** RegularExpression Id. */
  int LPAREN = 53;
  /** RegularExpression Id. */
  int RPAREN = 54;
  /** RegularExpression Id. */
  int RBRACK = 55;
  /** RegularExpression Id. */
  int RCURLY = 56;
  /** RegularExpression Id. */
  int SEMI = 57;
  /** RegularExpression Id. */
  int ASSIGN = 58;
  /** RegularExpression Id. */
  int ALSHIFT = 59;
  /** RegularExpression Id. */
  int ALSHIFT_ASSIGN = 60;
  /** RegularExpression Id. */
  int AND = 61;
  /** RegularExpression Id. */
  int AND_ASSIGN = 62;
  /** RegularExpression Id. */
  int ARSHIFT = 63;
  /** RegularExpression Id. */
  int ARSHIFT_ASSIGN = 64;
  /** RegularExpression Id. */
  int COLON = 65;
  /** RegularExpression Id. */
  int DEC = 66;
  /** RegularExpression Id. */
  int DIV = 67;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 68;
  /** RegularExpression Id. */
  int EQUAL = 69;
  /** RegularExpression Id. */
  int GE = 70;
  /** RegularExpression Id. */
  int GT = 71;
  /** RegularExpression Id. */
  int INC = 72;
  /** RegularExpression Id. */
  int LAND = 73;
  /** RegularExpression Id. */
  int LE = 74;
  /** RegularExpression Id. */
  int LT = 75;
  /** RegularExpression Id. */
  int LNOT = 76;
  /** RegularExpression Id. */
  int LOR = 77;
  /** RegularExpression Id. */
  int LRSHIFT = 78;
  /** RegularExpression Id. */
  int LRSHIFT_ASSIGN = 79;
  /** RegularExpression Id. */
  int MINUS = 80;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 81;
  /** RegularExpression Id. */
  int NOT = 82;
  /** RegularExpression Id. */
  int NOT_EQUAL = 83;
  /** RegularExpression Id. */
  int OR = 84;
  /** RegularExpression Id. */
  int OR_ASSIGN = 85;
  /** RegularExpression Id. */
  int PLUS = 86;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 87;
  /** RegularExpression Id. */
  int QUESTION = 88;
  /** RegularExpression Id. */
  int REM = 89;
  /** RegularExpression Id. */
  int REM_ASSIGN = 90;
  /** RegularExpression Id. */
  int STAR = 91;
  /** RegularExpression Id. */
  int STAR_ASSIGN = 92;
  /** RegularExpression Id. */
  int XOR = 93;
  /** RegularExpression Id. */
  int XOR_ASSIGN = 94;
  /** RegularExpression Id. */
  int IDENTIFIER = 95;
  /** RegularExpression Id. */
  int LETTER = 96;
  /** RegularExpression Id. */
  int DIGIT = 97;
  /** RegularExpression Id. */
  int DIGITS = 98;
  /** RegularExpression Id. */
  int SUFFIX = 99;
  /** RegularExpression Id. */
  int EXPONENT = 100;
  /** RegularExpression Id. */
  int INT_LITERAL = 101;
  /** RegularExpression Id. */
  int LONG_LITERAL = 102;
  /** RegularExpression Id. */
  int DOUBLE_LITERAL = 103;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 104;
  /** RegularExpression Id. */
  int STRING_LITERAL = 105;
  /** RegularExpression Id. */
  int ESC = 106;
  /** RegularExpression Id. */
  int ERROR = 107;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<END_COMMENT>",
    "<COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"continue\"",
    "\"char\"",
    "\"class\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"finally\"",
    "\"for\"",
    "\"if\"",
    "\"import\"",
    "\"implements\"",
    "\"interface\"",
    "\"instanceof\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"{\"",
    "\"(\"",
    "\")\"",
    "\"]\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"<<\"",
    "\"<<=\"",
    "\"&\"",
    "\"&=\"",
    "\">>\"",
    "\">>=\"",
    "\":\"",
    "\"--\"",
    "\"/\"",
    "\"/=\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"<\"",
    "\"!\"",
    "\"||\"",
    "\">>>\"",
    "\">>>=\"",
    "\"-\"",
    "\"-=\"",
    "\"~\"",
    "\"!=\"",
    "\"|\"",
    "\"|=\"",
    "\"+\"",
    "\"+=\"",
    "\"?\"",
    "\"%\"",
    "\"%=\"",
    "\"*\"",
    "\"*=\"",
    "\"^\"",
    "\"^=\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DIGITS>",
    "<SUFFIX>",
    "<EXPONENT>",
    "<INT_LITERAL>",
    "<LONG_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
